"""add collection model

Revision ID: d94da73394a7
Revises: b1677d1bb134
Create Date: 2026-07-02 20:12:50.962032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94da73394a7'
down_revision = 'b1677d1bb134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=100), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['credential.pid'], ),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('pid', 'collection_name', name='unique_collection'),
    if_not_exists=True
    )
    with op.batch_alter_table('userbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_userbook_cid', 'collection', ['cid'], ['cid'])
        batch_op.drop_column('collection')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collection', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cid')

    op.drop_table('collection')
    # ### end Alembic commands ###
