"""add friendship table

Revision ID: f681e7e7beb7
Revises: d94da73394a7
Create Date: 2026-07-02 23:45:29.156531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f681e7e7beb7'
down_revision = 'd94da73394a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('responded_at', sa.Date(), nullable=True),
    sa.CheckConstraint('sender_id != receiver_id', name='check_no_self_friendship'),
    sa.ForeignKeyConstraint(['receiver_id'], ['credential.pid'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['credential.pid'], ),
    sa.PrimaryKeyConstraint('fid'),
    sa.UniqueConstraint('sender_id', 'receiver_id', name='unique_friend_request')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
